relevance_keywords:
  - safety
  - incident
  - delay
  - weather
  - turbulence
  - atc
  - operation
  - notam
  - compliance
  - route
  - network
  - schedule
  - demand
  - expansion
  - fleet
  - delivery
  - boeing
  - airbus
  - engine
  - mro
  - aircraft
  - retrofit
  - order
  - regulator
  - policy
  - faa
  - easa
  - iata
  - rule
  - standard
  - certification

sensitive_keywords:
  - crash
  - fatal
  - dead
  - black box

sensational_words:
  - breaking
  - shocking
  - bombshell
  - must-see

blocked_domains:
  - freeportjournalstandard.com

pilot_signal_keywords:
  - aviation
  - airline
  - aircraft
  - flight
  - airport
  - airspace
  - runway
  - notam
  - atc
  - faa
  - easa
  - iata
  - icao
  - ntsb
  - airworthiness
  - service bulletin
  - incident
  - turbulence
  - diversion
  - go-around

pilot_entity_keywords:
  - faa
  - easa
  - icao
  - iata
  - ntsb
  - boeing
  - airbus
  - delta
  - united
  - american airlines
  - lufthansa
  - emirates
  - singapore airlines
  - qatar airways
  - british airways
  - cathay pacific
  - ryanair
  - southwest

hard_reject_keywords:
  - stock
  - shares
  - dividend
  - market cap
  - ipo
  - earnings
  - celebrity
  - luxury lounge
  - loyalty program
  - frequent flyer
  - meal service
  - tourism

pilot_allowed_source_ids:
  - iata_press_web
  - faa_newsroom_web
  - airbus_newsroom_web
  - boeing_newsroom_web
  - flightglobal_news_web
  - delta_news
  - aerotime
  - flightglobal
  - leeham_news
  - aviation_source
  - the_aviationist
  - simple_flying
  - view_from_wing
  - onemileatatime
  - iata_press
  - faa_news
  - easa_news
  - boeing_news
  - airbus_news
  - reuters_aerospace_web
  - ain_online_web
  - ntsb_press_web
  - easa_newsroom_web

pilot_allowed_domains:
  - iata.org
  - faa.gov
  - airbus.com
  - boeing.com
  - boeing.mediaroom.com
  - flightglobal.com
  - simpleflying.com
  - aviationsourcenews.com
  - aerotime.aero
  - theaviationist.com
  - onemileatatime.com
  - viewfromthewing.com
  - reuters.com
  - ainonline.com
  - ntsb.gov
  - easa.europa.eu
